services:
  directus:
    image: directus/directus:10.12.1
    volumes:
      - ./backend/database:/directus/database:rw
      - ./backend/uploads:/directus/uploads:rw
      - ./backend/extensions:/directus/extensions:rw
    environment:
      SECRET: "z9mM?KE7!rAmzrzB"
      ADMIN_EMAIL: "michaelmaroske@gmail.com"
      ADMIN_PASSWORD: "chickenbus"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: "true"
      CORS_ENABLED: "true"
      CORS_ALLOWED_ORIGINS: "*"
    ports:
      - "8055:8055"
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend/dockerfile
    volumes:
      - ./frontend/build:/app/build
    working_dir: /app
    environment:
      NODE_ENV: "production"
    ports:
      - "3000:3000"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
